version: "3.8"

services:
  db:
    image: postgres:14
    container_name: myapp_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: myapp_app
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/mydb
      - OPENAI_API_KEY=${OPENAI_API_KEY} 
      - OPENAI_ORG_ID=${OPENAI_ORG_ID} 
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
